name: Run rune on ubuntu with docker and crictl test

# Controls when the action will run. Triggers the workflow on pull request labeled testing-before-checkin.
on:
  pull_request_target:
    types: labeled

jobs:
  # TODO: add rune circtl test on ubuntu image.
  rune_ubuntu:
    if: ${{ contains(github.event.pull_request.labels.*.name, 'testing-before-checkin') }}
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
      with:
        ref: refs/pull/${{ github.event.pull_request.number }}/merge

      # We usually update rune.spec to the latest version before release. Therefore we get the latest version according to rune.spec.
    - name: Get version
      run: wget https://raw.githubusercontent.com/occlum/occlum/master/src/pal/include/occlum_version.h;
        echo "OCCLUM_VERSION=$(grep 'Version =' occlum_version.h | awk '{print $4}')" >> $GITHUB_ENV && rm -f occlum_version.h;
        echo "RUNE_VERSION=$(grep 'Version:' rune/dist/rpm/rune.spec | awk '{print $2}')" >> $GITHUB_ENV;
        echo "CPU_NUM=$(grep 'processor' /proc/cpuinfo | sort -u | wc -l)" >> $GITHUB_ENV

    - name: Create ubuntu container
      run: |
        ubuntu=$(docker run -itd --privileged --rm --net host --device /dev/isgx -v $GITHUB_WORKSPACE:/root/inclavare-containers occlum/occlum:$OCCLUM_VERSION-ubuntu18.04)
        echo "ubuntu=$ubuntu" >> $GITHUB_ENV

    - name: Install dependencies on ubuntu
      run: docker exec $ubuntu bash -c "apt-get update;
        apt-get install libseccomp-dev;
        cd /root && wget https://dl.google.com/go/go1.14.2.linux-amd64.tar.gz;
        tar -zxvf /root/go1.14.2.linux-amd64.tar.gz -C /usr/lib;
        echo 'export GOROOT=/usr/lib/go' >> /etc/profile;
        echo 'export GOPATH=/root/gopath' >> /etc/profile;
        echo 'export PATH=\$GOROOT/bin:\$PATH:\$GOPATH/bin' >> /etc/profile;
        echo 'export GOPROXY="https://mirrors.aliyun.com/goproxy,direct"' >>/etc/profile;
        echo 'export PKG_CONFIG_PATH=/usr/lib/pkgconfig' >>/etc/profile;
        echo 'export GO111MODULE=on' >>/etc/profile"

    - name: Build and install binaries on ubuntu
      run: docker exec $ubuntu bash -c "source /etc/profile;
        cd /root && cp -r inclavare-containers inclavare-containers-$RUNE_VERSION; 
        cd inclavare-containers-$RUNE_VERSION;
        make -j${CPU_NUM} && make install -j${CPU_NUM}"

    - name: Install and configure docker on ubuntu
      run: |
        docker exec $ubuntu bash -c "apt-get install -y apt-transport-https ca-certificates curl software-properties-common;
        curl -fsSL https://mirrors.aliyun.com/docker-ce/linux/ubuntu/gpg | apt-key add -;
        add-apt-repository 'deb [arch=amd64] https://mirrors.aliyun.com/docker-ce/linux/ubuntu bionic stable';
        apt-get update && apt-get install -y docker-ce"

        docker exec $ubuntu bash -c "mkdir -p /etc/docker;
        cat <<- EOF >/etc/docker/daemon.json
        {
            \"runtimes\":{
                \"rune\":{
                    \"path\":\"/usr/local/bin/rune\",
                    \"runtimeArgs\":[]
                  }
              },
              \"storage-driver\": \"vfs\"
        }
        EOF"

        docker exec $ubuntu bash -c "service docker start"

    - name: Build Occlum Application Image on ubuntu
      run: |
        docker exec $ubuntu bash -c "cat <<- EOF >/root/hello_world.c
        "#include\<stdio.h\>"
        int main (void)
        {
            printf(\"Hello World\n\");
            return 0;
        }
        EOF"

        docker exec $ubuntu bash -c "occlum-gcc -o hello_world hello_world.c;
        occlum new occlum_instance && cd occlum_instance;
        cp ../hello_world image/bin/ && occlum build;
        occlum package occlum_instance.tar.gz"

        docker exec $ubuntu bash -c "cat <<- EOF >/root/occlum_instance/Dockerfile
        FROM scratch
        ADD occlum_instance.tar.gz /
        ENTRYPOINT [\"/bin/hello_world\"]
        EOF"

        docker exec $ubuntu bash -c "cd /root/occlum_instance;
        docker build . -t occlum-app"

    - name: Build skeleton image on ubuntu
      run: |
        docker exec $ubuntu bash -c "apt-get install -y libprotoc-dev binutils-dev;
        wget https://github.com/protobuf-c/protobuf-c/archive/v1.3.1.tar.gz; tar -zxvf v1.3.1.tar.gz;
        cd protobuf-c-1.3.1; ./autogen.sh;
        source /etc/profile; ./configure && make -j${CPU_NUM} && make install -j${CPU_NUM};
        apt-get remove -y libprotobuf-dev; apt -y autoremove;
        cd /root/inclavare-containers/rune/libenclave/internal/runtime/pal/skeleton
        make -j${CPU_NUM} && cp liberpal-skeleton-v*.so /usr/lib;
        cat >Dockerfile <<-EOF
        FROM scratch

        COPY encl.bin /
        COPY encl.ss /
        ENTRYPOINT [\"dummy\"]
        EOF"

        docker exec $ubuntu bash -c "cd /root/inclavare-containers/rune/libenclave/internal/runtime/pal/skeleton;
        docker build . -t skeleton-enclave"

    - name: Run Occlum image on ubuntu
      run: docker exec $ubuntu bash -c "docker run -i --rm --runtime=rune -e ENCLAVE_TYPE=intelSgx -e ENCLAVE_RUNTIME_PATH=/opt/occlum/build/lib/libocclum-pal.so -e ENCLAVE_RUNTIME_ARGS=occlum_instance occlum-app"

    - name: Run skeleton-v1.so on ubuntu
      if: always()
      run: docker exec $ubuntu bash -c "source /etc/profile; docker run -i --rm --runtime=rune -e ENCLAVE_TYPE=intelSgx -e ENCLAVE_RUNTIME_PATH=/usr/lib/liberpal-skeleton-v1.so -e ENCLAVE_RUNTIME_ARGS=debug skeleton-enclave"

    - name: Run skeleton-v2.so on ubuntu
      if: always()
      run: docker exec $ubuntu bash -c "source /etc/profile; docker run -i --rm --runtime=rune -e ENCLAVE_TYPE=intelSgx -e ENCLAVE_RUNTIME_PATH=/usr/lib/liberpal-skeleton-v2.so -e ENCLAVE_RUNTIME_ARGS=debug skeleton-enclave"

    - name: Run skeleton-v3.so on ubuntu
      if: always()
      run: docker exec $ubuntu bash -c "source /etc/profile; docker run -i --rm --runtime=rune -e ENCLAVE_TYPE=intelSgx -e ENCLAVE_RUNTIME_PATH=/usr/lib/liberpal-skeleton-v3.so -e ENCLAVE_RUNTIME_ARGS=debug skeleton-enclave"

    - name: Run Occlum bundle on ubuntu
      if: always()
      run: |
        docker exec $ubuntu bash -c "mkdir rootfs;
        docker create --name occlum-app occlum-app;
        docker export occlum-app | tar -C rootfs -xvf -;
        rune spec;
        sed -i '4 c \"terminal\": false,' config.json;
        sed -i '16 c \"cwd\": \"\/\",' config.json;
        sed -i 's#\"sh\"#\"/bin/hello_world\"#g' config.json;
        sed -i 's#\"debug\"#\"occlum_instance\"#g' config.json;
        sed -i 's#/var/run/rune/liberpal-skeleton-v2.so#/opt/occlum/build/lib/libocclum-pal.so#g' config.json;
        rune --debug run occlum-app && rm -rf rootfs config.json"

    - name: Create skeleton bundle on ubuntu
      if: always()
      run: docker exec $ubuntu bash -c "mkdir rootfs;
        docker create --name skeleton-enclave skeleton-enclave;
        docker export skeleton-enclave | tar -C rootfs -xvf -;
        cp /etc/resolv.conf rootfs/etc/resolv.conf"

    - name: Run skeleton v2 bundle on ubuntu
      if: always()
      run: |
        docker exec $ubuntu bash -c "mkdir -p /var/run/rune;
        cp /usr/lib/liberpal-skeleton-v2.so /var/run/rune/liberpal-skeleton-v2.so;
        rune spec;
        sed -i '4 c \"terminal\": false,' config.json;
        sed -i '16 c \"cwd\": \"\/\",' config.json;
        rune --debug run ra"

    - name: Generate skeleton ra config.json on ubuntu
      if: always()
      run: | 
        docker exec $ubuntu bash -c "sed -i '161,163d' config.json;
        sed -i 's/\/var\/run\/rune\/liberpal-skeleton-v2.so/\/usr\/lib\/liberpal-skeleton-v3.so/g' config.json;
        sed -i '10 c  \"sh\",\"wait_timeout\",\"6000\"' config.json;
        sed -i '144 a \"enclave.attestation.ra_epid_is_linkable\": \"false\",' config.json;
        sed -i '144 a \"enclave.attestation.ra_epid_subscription_key\": \"${{ secrets.SUB_KEY }}\",' config.json;
        sed -i '144 a \"enclave.attestation.ra_epid_spid\": \"${{ secrets.SPID }}\",' config.json;
        sed -i '144 a \"enclave.attestation.ra_type\":\"EPID\",' config.json;"

    - name: Run skeleton v3 bundle on ubuntu
      if: always()
      run: docker exec $ubuntu bash -c "rune --debug run skeleton-enclave-container" &

    - name: Get remote report with rune attest command with skeleton on ubuntu
      if: always()
      run: docker exec $ubuntu bash -c "sleep 10;
        rune --debug attest --isRA --linkable=false --spid=${{ secrets.SPID }} --subscription-key=${{ secrets.SUB_KEY }} skeleton-enclave-container"

    - name: Get local report with rune attest command with skeleton on ubuntu
      if: always()
      run: docker exec $ubuntu bash -c "rune --debug attest --reportFile=/report.bin skeleton-enclave-container"

    - name: Get target info with sgx-tools on ubuntu
      if: always()
      run: docker exec $ubuntu bash -c "cd rootfs;
        sgx-tools -verbose gen-qe-target-info"

    - name: Get quote with sgx-tools on ubuntu
      if: always()
      run: docker exec $ubuntu bash -c "cd rootfs;
        sgx-tools -verbose gen-quote --report report.bin --spid=${{ secrets.SPID }}"

    - name: Get remote report with sgx-tools on ubuntu
      if: always()
      run: docker exec $ubuntu bash -c "cd rootfs;
        sgx-tools -verbose get-ias-report --quote quote.bin --spid=${{ secrets.SPID }} --subscription-key=${{ secrets.SUB_KEY }}"

    - name: Kill the container
      if: always()
      run: docker stop $ubuntu
