name: Run rune on ubuntu with docker and crictl test

# Controls when the action will run. Triggers the workflow on pull request labeled testing-before-checkin.
on:
  pull_request:
    types: labeled

jobs:
  # TODO: add rune circtl test on ubuntu image.
  rune_ubuntu:
    if: ${{ contains(github.event.pull_request.labels.*.name, 'testing-before-checkin') }}
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v1

      # We usually update rune.spec to the latest version before release. Therefore we get the latest version according to rune.spec.
    - name: Get version
      run: wget https://raw.githubusercontent.com/occlum/occlum/master/src/pal/include/occlum_version.h;
        echo "OCCLUM_VERSION=$(grep 'Version =' occlum_version.h | awk '{print $4}')" >> $GITHUB_ENV && rm -f occlum_version.h;
        echo "RUNE_VERSION=$(grep 'Version:' rune/dist/rpm/rune.spec | awk '{print $2}')" >> $GITHUB_ENV;
        echo "CPU_NUM=$(grep 'processor' /proc/cpuinfo | sort -u | wc -l)" >> $GITHUB_ENV

    - name: Create ubuntu container
      run: |
        ubuntu=$(docker run -itd --privileged --rm --net host --device /dev/isgx -v $GITHUB_WORKSPACE:/root/inclavare-containers occlum/occlum:$OCCLUM_VERSION-ubuntu18.04)
        echo "ubuntu=$ubuntu" >> $GITHUB_ENV

    - name: Install dependencies on ubuntu
      run: docker exec $ubuntu bash -c "apt-get update;
        apt-get install libseccomp-dev;
        cd /root && wget https://dl.google.com/go/go1.14.2.linux-amd64.tar.gz;
        tar -zxvf /root/go1.14.2.linux-amd64.tar.gz -C /usr/lib;
        echo 'export GOROOT=/usr/lib/go' >> /etc/profile;
        echo 'export GOPATH=/root/gopath' >> /etc/profile;
        echo 'export PATH=\$GOROOT/bin:\$PATH:\$GOPATH/bin' >> /etc/profile;
        echo 'export GOPROXY="https://mirrors.aliyun.com/goproxy,direct"' >>/etc/profile;
        echo 'export PKG_CONFIG_PATH=/usr/lib/pkgconfig' >>/etc/profile;
        echo 'export GO111MODULE=on' >>/etc/profile"

    - name: Build and install rune deb
      run: docker exec $ubuntu bash -c "cd /root;
        cp -r inclavare-containers inclavare-containers-$RUNE_VERSION;
        tar zcf v$RUNE_VERSION.tar.gz inclavare-containers-$RUNE_VERSION;
        pushd /root/inclavare-containers-$RUNE_VERSION;
        echo "$RUNE_VERSION" > VERSION;
        sed -i '17 d' rune/dist/deb/build.sh;
        sed -i '17icp /root/v*.tar.gz \$DEBBUILD_DIR' rune/dist/deb/build.sh;
        source /etc/profile;
        make package components=rune;
        dpkg -i rune_$RUNE_VERSION-1_amd64.deb;
        popd"

    - name: Install and configure docker on ubuntu
      run: |
        docker exec $ubuntu bash -c "apt-get install -y apt-transport-https ca-certificates curl software-properties-common;
        curl -fsSL https://mirrors.aliyun.com/docker-ce/linux/ubuntu/gpg | apt-key add -;
        add-apt-repository 'deb [arch=amd64] https://mirrors.aliyun.com/docker-ce/linux/ubuntu bionic stable';
        apt-get update && apt-get install -y docker-ce"

        docker exec $ubuntu bash -c "mkdir -p /etc/docker;
        cat <<- EOF >/etc/docker/daemon.json
        {
            \"runtimes\":{
                \"rune\":{
                    \"path\":\"/usr/local/bin/rune\",
                    \"runtimeArgs\":[]
                  }
              },
              \"storage-driver\": \"vfs\"
        }
        EOF"

        docker exec $ubuntu bash -c "service docker start"

    - name: Build Occlum Application Image on ubuntu
      run: |
        docker exec $ubuntu bash -c "cat <<- EOF >/root/hello_world.c
        "#include\<stdio.h\>"
        int main (void)
        {
            printf(\"Hello World\n\");
            return 0;
        }
        EOF"

        docker exec $ubuntu bash -c "occlum-gcc -o hello_world hello_world.c;
        occlum new occlum_instance && cd occlum_instance;
        cp ../hello_world image/bin/ && occlum build;
        occlum package occlum_instance.tar.gz"

        docker exec $ubuntu bash -c "cat <<- EOF >/root/occlum_instance/Dockerfile
        FROM centos:8.1.1911
        RUN mkdir -p /run/rune
        WORKDIR /run/rune
        ADD occlum_instance.tar.gz /run/rune
        ENTRYPOINT [\"/bin/hello_world\"]
        EOF"

        docker exec $ubuntu bash -c "cd /root/occlum_instance;
        docker build . -t occlum-app"

    - name: Build skeleton image on ubuntu
      run: |
        docker exec $ubuntu bash -c "apt-get install -y libprotoc-dev binutils-dev;
        wget https://github.com/protobuf-c/protobuf-c/archive/v1.3.1.tar.gz; tar -zxvf v1.3.1.tar.gz;
        cd protobuf-c-1.3.1; ./autogen.sh;
        source /etc/profile; ./configure && make -j${CPU_NUM} && make install -j${CPU_NUM};
        apt-get remove -y libprotobuf-dev; apt -y autoremove;
        cd /root/inclavare-containers/rune/libenclave/internal/runtime/pal/skeleton
        make -j${CPU_NUM} && cp liberpal-skeleton-v*.so /usr/lib;
        cat >Dockerfile <<-EOF
        FROM centos:8.1.1911

        RUN mkdir -p /run/rune
        WORKDIR /run/rune

        COPY encl.bin .
        COPY encl.ss .
        EOF"

        docker exec $ubuntu bash -c "cd /root/inclavare-containers/rune/libenclave/internal/runtime/pal/skeleton;
        docker build . -t skeleton-enclave"

    - name: Run Occlum image on ubuntu
      run: docker exec $ubuntu bash -c "docker run -i --rm --runtime=rune -e ENCLAVE_TYPE=intelSgx -e ENCLAVE_RUNTIME_PATH=/opt/occlum/build/lib/libocclum-pal.so -e ENCLAVE_RUNTIME_ARGS=occlum_instance occlum-app"

    - name: Run skeleton-v1.so on ubuntu
      if: always()
      run: docker exec $ubuntu bash -c "source /etc/profile; docker run -i --rm --runtime=rune -e ENCLAVE_TYPE=intelSgx -e ENCLAVE_RUNTIME_PATH=/usr/lib/liberpal-skeleton-v1.so -e ENCLAVE_RUNTIME_ARGS=debug skeleton-enclave"

    - name: Run skeleton-v2.so on ubuntu
      if: always()
      run: docker exec $ubuntu bash -c "source /etc/profile; docker run -i --rm --runtime=rune -e ENCLAVE_TYPE=intelSgx -e ENCLAVE_RUNTIME_PATH=/usr/lib/liberpal-skeleton-v2.so -e ENCLAVE_RUNTIME_ARGS=debug skeleton-enclave"

    - name: Run skeleton-v3.so on ubuntu
      if: always()
      run: docker exec $ubuntu bash -c "source /etc/profile; docker run -i --rm --runtime=rune -e ENCLAVE_TYPE=intelSgx -e ENCLAVE_RUNTIME_PATH=/usr/lib/liberpal-skeleton-v3.so -e ENCLAVE_RUNTIME_ARGS=debug skeleton-enclave"

    - name: Kill the container
      if: always()
      run: docker stop $ubuntu
